### ISSUE TITLE
Link dead for download compiled code

### ISSUE THREAD

**Issue by gchevignon** [steineggerlab/Metabuli-App#7]
Hello,
All the links to download compiled codes seems dead whereas it works for source code ...
Best

**Comment by snjlee58** [comment]
Hello, thank you for bringing this up! 

Just to clarify, are you referring to the precompiled apps available in the GitHub Releases page? I've checked the links (for Mac and Windows) and they appear to be working on my end, but it's possible there could be an issue we're not seeing. Could you provide more details about the problem, like any error messages or the browser and operating system you are using?

I will do my best to help resolve this!

**Comment by gchevignon** [comment]
Yes it was the precompiled apps available in the GitHub Releases page.
But it is working now !
Sorry for that 
Best

**Comment by snjlee58** [comment]
Oh thats great to hear! Thanks for the feedback!
